### ISSUE TITLE
Missing asset files and weird fog + lighting?

### ISSUE THREAD

**Issue by dljr-github** [JuanDiegoMontoya/moldy-broccoli#1]
There appears to be missing asset files. Upon loading my own assets however, It seems that lighting and fog is broken? SSR doesn't seem to be working either. 
![image](https://github.com/JuanDiegoMontoya/GLest-Rendererer/assets/40004424/2f6073fb-d3d5-4326-a821-27eed3b49602)

**Comment by JuanDiegoMontoya** [comment]
Hi @kawaiipooptato, thanks for the issue! I ran the project locally to see if my image looks the same, and indeed it does.

I intentionally included no assets in the repo, not really expecting others to run this project (though it's good to see that it can work. I appreciate the effort).

While the fog is janky and unrealistic, it is in fact working as intended. I don't believe it takes into account lighting at all. I also implemented it before I understood how scattering and transmission worked.

The SSR also works (at least as far as an SSR implementation can) for me. Try adding the PBR sphere grid (under environment->draw PBR grid) or overriding the global material with a low-roughness material. Here is an example (note that the colors are off due to taking a screen capture of an HDR monitor):
![sponza, but everything is blue](https://github.com/JuanDiegoMontoya/GLest-Rendererer/assets/38368197/0aa74456-e7e6-48c9-9579-5f3debeaed05)

**Comment by dljr-github** [comment]
Hi @JuanDiegoMontoya,

Thank you for the detailed response! I came across your project while exploring bindless textures and multi-draw indirect, and I must say, it's been quite insightful. Your efforts in sharing this work are genuinely appreciated.

Upon adjusting the settings as you mentioned, I can confirm that the SSR is functioning as expected. My apologies for the oversight earlier.

If it's not too much trouble, would you consider uploading the original assets? I believe it would benefit many, including myself, who are keen on replicating the visuals from your screenshots.

Thanks again for your time and assistance!

**Comment by JuanDiegoMontoya** [comment]
I pushed the assets that are loaded by default. Now it should work without having to add your own.

**Comment by dljr-github** [comment]
Thank you so much once again!
